---
- hosts: localhost
  gather_facts: no
  vars:
    networks:
    - name: example-cnf-net1
      count: 2
    cluster_name: ''
    operator_version: v0.2.4
    app_version: v0.2.2
    registry_url: quay.io
    repo_name: rh-nfv-int
    testpmd_node_count: 1
    ansible_operator_meta:
      name: testpmd-1
      namespace: example-cnf
  roles:
  - testpmd
