apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: example-cnf
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testpmds.examplecnf.openshift.io
spec:
  group: examplecnf.openshift.io
  names:
    kind: TestPMD
    listKind: TestPMDList
    plural: testpmds
    singular: testpmd
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: TestPMD is the Schema for the testpmds API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of TestPMD
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of TestPMD
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testpmd-operator-controller-manager
  namespace: example-cnf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testpmd-operator-leader-election-role
  namespace: example-cnf
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testpmd-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - pods/exec
  - pods/log
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - testpmds
  - testpmds/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testpmd-operator-leader-election-rolebinding
  namespace: example-cnf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testpmd-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: testpmd-operator-controller-manager
  namespace: example-cnf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testpmd-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testpmd-operator-manager-role
subjects:
- kind: ServiceAccount
  name: testpmd-operator-controller-manager
  namespace: example-cnf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: testpmd-operator-controller-manager
  namespace: example-cnf
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
        example-cnf-type: testpmd-operator
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --leader-election-id=testpmd-operator
        env:
        - name: ANSIBLE_GATHERING
          value: explicit
        image: quay.io/rh-nfv-int/testpmd-operator:v0.2.4
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the postStart handler"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the preStop handler"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6789
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6789
          initialDelaySeconds: 5
          periodSeconds: 10
        terminationMessagePolicy: FallbackToLogsOnError
      serviceAccountName: testpmd-operator-controller-manager
      terminationGracePeriodSeconds: 10
