kind: Deployment
apiVersion: apps/v1
metadata:
  name: "loadbalancer"
  namespace: "{{ ansible_operator_meta.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      example-cnf-type: lb-app
      restart-on-reboot: "true"
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
{% for network in networks %}
{% set outer_loop = loop %}
{% for count in range(network.count) %}
          {
            "name": "{{ network.name }}",
{% if network.mac|default([])|length == network.count %}
            "mac": "{{ network.mac[loop.index - 1] }}",
{% endif %}
            "namespace": "{{ ansible_operator_meta.namespace }}"
          }{% if loop.index < network.count or outer_loop.index < network_name_list|length %},{% endif %}
{% endfor %}
{% endfor %}
        ]'
{% if runtime_class_name is defined and runtime_class_name|length %}
        irq-load-balancing.crio.io: "disable"
        cpu-load-balancing.crio.io: "disable"
{% endif %}
      labels:
        example-cnf-type: lb-app
        restart-on-reboot: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: example-cnf-type
                operator: In
                values:
                - cnf-app
                - pkt-gen
            topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        runAsUser: 56560
      serviceAccountName: loadbalancer-account
{% if runtime_class_name is defined and runtime_class_name|length %}
      runtimeClassName: "{{ runtime_class_name }}"
{% endif %}
{% if numa_aware_topology is defined and numa_aware_topology | length %}
      schedulerName: "{{ numa_aware_topology }}"
{% endif %}
      containers:
      - name: loadbalancer
        ports:
        - name: "http-probe"
          containerPort: 8095
        command: ["/usr/local/bin/example-cnf/testpmd-wrapper"]
        args:
        - "--socket-mem {{ socket_memory }}"
        - "-n {{ memory_channels }}"
        - "--proc-type auto"
        - "--file-prefix pg"
        - "--"
        - "--disable-rss"
        - "--nb-cores={{ forwarding_cores }}"
        - "--rxq={{ rx_queues }}"
        - "--txq={{ tx_queues }}"
        - "--rxd={{ rx_descriptors }}"
        - "--txd={{ tx_descriptors }}"
        - "--auto-start"
{% for mac in packet_generator_macs %}
        - "--eth-peer={{ loop.index -1 }},{{ mac }}"
{% endfor %}
        - "--forward-mode=lb"
        image: "{{ image_testpmd }}"
        imagePullPolicy: "{{ image_pull_policy }}"
        securityContext:
          runAsNonRoot: true
          runAsUser: 56560
          #readOnlyRootFilesystem: true
{% if privileged %}
          privileged: true
{% else %}
          capabilities:
            add: ["IPC_LOCK", "NET_ADMIN", "AUDIT_WRITE"]
{% endif %}
        resources:
          limits:
            hugepages-1Gi: {{ hugepage_1gb_count }}
            memory: {{ memory }}
            cpu: {{ cpu }}
{% for key, value in network_resources.items() %}
            {{ key }}: {{ value }}
{% endfor %}
          requests:
            hugepages-1Gi: {{ hugepage_1gb_count }}
            memory: {{ memory }}
            cpu: {{ cpu }}
{% for key, value in network_resources.items() %}
            {{ key }}: {{ value }}
{% endfor %}
        volumeMounts:
        - name: hugepage
          mountPath: /dev/hugepages
        - name: log-dir
          mountPath: /var/log/testpmd
        - name: lib-dir
          mountPath: /var/lib/testpmd
        env:
        - name: NETWORK_NAME_LIST
          value: "{{ network_resources.keys()|list|join(',') }}"
        - name: CNF_APP_NETWORK_NAME_LIST
          value: "{{ cnf_app_network_resources.keys()|list|join(',') }}"
        - name: TESTPMD_CPU_COUNT
          value: "{{ cpu }}"
        - name: MODE
          value: "lb"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CR_NAME
          value: "{{ ansible_operator_meta.name }}"
{% for key, value in environments.items() %}
        - name: {{ key }}
          value: "{{ value }}"
{% endfor %}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the postStart handler"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the preStop handler"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8095
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8095
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /startz
            port: 8095
          initialDelaySeconds: 30
          periodSeconds: 10
        terminationMessagePolicy: FallbackToLogsOnError
      - name: listener
        ports:
        - name: "http-probe"
          containerPort: 8096
        image: "{{ image_listener }}"
        imagePullPolicy: "{{ image_pull_policy }}"
        securityContext:
          runAsNonRoot: true
          runAsUser: 56560
          #readOnlyRootFilesystem: true
        resources:
          limits:
            memory: "512Mi"
            cpu: 2
          requests:
            memory: "512Mi"
            cpu: 2
        volumeMounts:
        - name: log-dir
          mountPath: /var/log/testpmd
        - name: lib-dir
          mountPath: /var/lib/testpmd
        env:
        - name: NETWORK_NAME_LIST
          value: "{{ network_resources.keys()|list|join(',') }}"
        - name: CNF_APP_NETWORK_NAME_LIST
          value: "{{ cnf_app_network_resources.keys()|list|join(',') }}"
        - name: TESTPMD_CPU_COUNT
          value: "{{ cpu }}"
        - name: ETH_PEER_MACS
          value: "{{ packet_generator_macs }}"
        - name: MODE
          value: "lb"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CR_NAME
          value: "{{ ansible_operator_meta.name }}"
{% for key, value in environments.items() %}
        - name: {{ key }}
          value: "{{ value }}"
{% endfor %}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the postStart handler"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the preStop handler"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8096
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8096
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /startz
            port: 8096
          initialDelaySeconds: 30
          periodSeconds: 10
        terminationMessagePolicy: FallbackToLogsOnError
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
      - name: log-dir
        emptyDir: {}
      - name: lib-dir
        emptyDir: {}
