---
# if replica = 1, recommended not to set maxUnavailable to 0 or 0% and minAvailable to 100%
# https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/adding-pod-disruption-budgets.md#limitations-on-pod-disruption-budgets
apiVersion: v1
kind: List
items:
  - apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: lb-app-pdb-min
      namespace: "{{ ansible_operator_meta.namespace }}"
    spec:
      minAvailable: 0
      selector:
        matchLabels:
          example-cnf-type: lb-app
  - apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: lb-app-pdb-max
      namespace: "{{ ansible_operator_meta.namespace }}"
    spec:
      maxUnavailable: 1
      selector:
        matchLabels:
          example-cnf-type: lb-app
