#!/bin/bash

set -x

# Define the function to add timestamp to log entries
echo_ts() {
  echo "$(date -u +"%Y-%m-%dT%H:%M:%S%z") $@"
}

CORE_COUNT=$1

if [ -z $CORE_COUNT ]; then
    echo_ts "Provide number cores as first parameter"
    exit 1
fi

cd $TREX_DIR
n=0
until [ "$n" -ge 5 ]
do
   ./_t-rex-64 -i --no-hw-flow-stat -c $CORE_COUNT
   n=$((n+1))
   sleep 5
done
echo_ts "Failed to start TRex Server on 5 retries..."
