#!/bin/bash

set -e

# Start lifecycle webserver in background
go run /usr/local/bin/webserver.go &

# Define the function to add timestamp to log entries
echo_ts() {
  echo "$(date -u +"%Y-%m-%dT%H:%M:%S%z") $@"
}

# direct variables
MODE=${MODE:="direct"}
LB_MACS=${LB_MACS:=""}

# environments
RUN_CONFIGURE=${run_configure:=1}
RUN_SERVER=${run_server:=1}
RUN_DELAY=${run_delay:=1}
# trex_core_count (trexCoreCount)

CORES=$(taskset -pc 1 | cut -d: -f2)

if [[ $RUN_CONFIGURE != "1" ]]; then
    echo_ts "Configure disabled for manual override, sleeping .."
    sleep infinity
fi

# Write TRex cfg file
if [[ $MODE == "lb" ]]; then
    if [ -z ${LB_MACS} ]; then
        echo_ts "ERROR: LB macs is empty in lb mode, cannot start server"
        sleep infinity
        exit 1
    fi
    trex-cfg-configure $CORES $LB_MACS
else
    trex-cfg-configure $CORES
fi

# Read the number of cores from the trex cfg
# It is required as input via -c arg (for binary_search scripts of trafficgen)
CORE_COUNT_CFG=$(grep ' c: ' /etc/trex_cfg.yaml | cut -d: -f2 | xargs)
NUM_PORTS=$(grep ' port_limit: ' /etc/trex_cfg.yaml | cut -d: -f 2 | xargs)

CORE_COUNT=${trex_core_count:=$CORE_COUNT_CFG}
# TREX_CPU env will be set on the pod spec with number of required cores
if [[ $((CORE_COUNT_CFG + 2)) != $TREX_CPU ]]; then
    # TEMP
    echo_ts "CORES=$((CORE_COUNT + 2))"
    echo_ts "TREX_CPU=$TREX_CPU"
    exit 1
fi

SERVER="/usr/local/bin/trex-server"
chmod +x $SERVER

if [[ $RUN_SERVER == "1" ]]; then
    sleep $RUN_DELAY
    #echo_ts "Starting TRex daemon server ..."
    #./trex_daemon_server start
    echo_ts "Starting TRex server ..."
    $SERVER $CORE_COUNT
else
    echo_ts "Skipping TRex server start, waiting ..."
    sleep infinity
fi
