kind: Job
apiVersion: batch/v1
metadata:
  name: "job-{{ ansible_operator_meta.name }}"
  namespace: "{{ ansible_operator_meta.namespace }}"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        example-cnf-type: pkt-gen-app
    spec:
      restartPolicy: Never
      containers:
      - name: trex-app
        image: "{{ image_app }}"
        imagePullPolicy: "{{ image_pull_policy }}"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
{% if trex_profile_config_map %}
        - name: profile
          mountPath: /opt/trexprofile
{% endif %}
        env:
        - name: MODE
          value: "{{ 'lb' if enable_lb|default(false) else 'direct' }}"
        - name: LB_MACS
          value: "{{ lb_macs|join(',') }}"
        - name: CR_NAME
          value: "{{ ansible_operator_meta.name }}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
{% for key, value in environments.items() %}
        - name: {{ key }}
          value: "{{ value }}"
{% endfor %}
        - name: TREX_SERVER_URL
          value: trex-server
{% if trex_profile_name %}
        - name: TREX_PROFILE_NAME
          value: "{{ trex_profile_name }}"
{% endif %}
{% if duration %}
        - name: DURATION
          value: "{{ duration }}"
{% endif %}
{% if packet_size %}
        - name: PACKET_SIZE
          value: "{{ packet_size }}"
{% endif %}
{% if packet_rate %}
        - name: PACKET_RATE
          value: "{{ packet_rate }}"
{% endif %}
      volumes:
      - name: varlog
        emptyDir: {}
{% if trex_profile_config_map %}
      - name: profile
        configMap:
          name: {{ trex_profile_config_map }}
{% endif %}
