#!/usr/bin/env python3

import sys

def main():
    data = ''
    with open('/sys/fs/cgroup/cpuset/cpuset.cpus') as f:
        data = f.read()

    out = []
    for item in data.split(','):
        if '-' in item:
            rng = item.split('-')
            for i in range(int(rng[0]), int(rng[1]) + 1):
                out.append(str(i))
        else:
            out.append(item)
    print(','.join(out))

if __name__ == "__main__":
    main()
