name: Quay

on:
  push:
    branches:
      - master

env:
  REGISTRY: quay.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1.4
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Build and Push the images
        run: |
          ORG=${GITHUB_REPOSITORY%/*}
          TAG=$(git tag --points-at HEAD)
          VERSION=${TAG/v/}
          make all ORG=${ORG} VERSION=${VERSION}
