---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testpmds.examplecnf.openshift.io
spec:
  group: examplecnf.openshift.io
  names:
    kind: TestPMD
    listKind: TestPMDList
    plural: testpmds
    singular: testpmd
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: TestPMD is the Schema for the testpmds API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of TestPMD
            type: object
            properties:
              privileged:
                description: Run the container in privileged mode
                type: boolean
              imagePullPolicy:
                description: Image pull policy for the TestPMD container
                type: string
                enum:
                - Always
                - IfNotPresent
                - Never
              ethpeerMaclist:
                description: List of MAC addresses for peer interfaces
                type: array
                items:
                  type: string
              size:
                description: Number of replicas for the TestPMD deployment
                type: integer
                minimum: 1
              networks:
                description: List of NetworkAttachmentDefinitions to attach to the pod
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: NetworkAttachmentDefinition name (namespace/name or name)
                      type: string
                    count:
                      description: Number of interfaces to request from this network
                      type: integer
                      minimum: 1
                      default: 1
                    mac:
                      description: Optional list of MAC addresses, one per interface
                      type: array
                      items:
                        type: string
                    ip:
                      description: Optional list of IP addresses, one per interface
                      type: array
                      items:
                        type: string
              reducedMode:
                description: Use reduced mode (1 to enable), limiting cores and doubling txd/rxd
                type: integer
                enum:
                - 0
                - 1
              runDeployment:
                description: Whether to run the deployment automation (0 to disable, 1 to enable)
                type: integer
                enum:
                - 0
                - 1
              runtime_class_name:
                description: Optional RuntimeClass to use for the pod
                type: string
              numa_aware_topology:
                description: Optional scheduler name for NUMA-aware topology
                type: string
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of TestPMD
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
