apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy/namespace.yaml
  - deploy/crds/examplecnf.openshift.io_testpmds_crd.yaml
  - deploy/crds/examplecnf.openshift.io_testpmdmacs_crd.yaml
  - deploy/service_account.yaml
  - deploy/role.yaml
  - deploy/role_binding.yaml
  - deploy/operator.yaml
  - deploy/scc.yaml
