# Helper file, this playbook is not used inside the operator
# This playbook is useful to runnin locally for easy development
# Command: ansible-playbook -i playbook.yaml -vv
---
- hosts: localhost
  gather_facts: no
  vars:
    ansible_operator_meta:
      name: trex-manual1
      namespace: example-cnf
    privileged: false
    image: quay.io/krsacme/trex-container-app:v0.0.1 
    imagePullPolicy: Always
    size: 1
    networks:
      - name: vfdpdk1
        count: 1
      - name: vfdpdk2
        count: 1
    command: ["sleep infinity"]

  tasks:
  - template:
      src: roles/trexconfig/templates/deployment.yml
      dest: /tmp/deployment.yaml
    vars:
      network_name_list: ["vfdpdk1","vfdpdk2"]
      hugepage_1gb_count: 3
      memory: 1000
      cpu: 4
      network_resources: {}
      dut_maclist: []
  - fail:
  - include_role:
      name: trex

