# Helper file, this playbook is not used inside the operator
# This playbook is useful to runnin locally for easy development
# Command: ansible-playbook -i playbook.yaml -vv
---
- hosts: localhost
  gather_facts: no
  vars:
    meta:
      name: testpmd1
      namespace: example-cnf
  tasks:
  - include_role:
      name: testpmd
    vars:
      #image: quay.io/krsacme/testpmd-container-app:nostart
      ethpeer_maclist:
        - 3c:fd:fe:79:2a:a0
        - 3c:fd:fe:79:2a:a1
      size: 1
      networks:
        - name: vfdpdk1
          mac: 20:04:0f:f1:88:01
          count: 1
        - name: vfdpdk2
          mac: 20:04:0f:f1:88:02
          count: 1
