#!/bin/bash

set -ex

if [ -z NETWORK_NAME_LIST ]; then
    echo "NETWORK_NAME_LIST is empty, exiting.."
    exit 1
fi

PCI=""
IFS=',' read -r -a NETWORK_ARRAY <<< "$NETWORK_NAME_LIST"

for item in "${NETWORK_ARRAY[@]}"; do
    IFS='/' read -r -a RES_ARRAY <<< "$item"
    NAME="PCIDEVICE_OPENSHIFT_IO_${RES_ARRAY[1]^^}"
    if [ -z ${!NAME} ]; then
        echo "Could not find ${NAME} with PCI address, exiting"
        exit 1
    fi
    IFS=',' read -r -a PCI_ARRAY <<< "${!NAME}"
    for pci_item in "${PCI_ARRAY[@]}"; do
        PCI+=" -w ${pci_item} "
    done
done

LCORES=$(cat /sys/fs/cgroup/cpuset/cpuset.cpus)
if [ -z $LCORES ]; then
    echo "Could not find cores, existing.."
    exit 1
fi

RUN="/usr/local/bin/testpmd-run"
echo "testpmd -l $LCORES $PCI $@ --stats-period 10" > $RUN
chmod +x $RUN

# Update the mac address with CR
testpmd-configure

testpmd-run &
sleep infinity
