---
# tasks file for TRexApp
- name: check if treconfig is available
  kubernetes.core.k8s_info:
    kind: TRexConfig
    api_version: examplecnf.openshift.io/v1
  register: trex_config
- name: fail if trexconfig is not created
  ansible.builtin.fail:
    msg: "wait for trexconfig resource"
  when: "trex_config.resources|length == 0"
- ansible.builtin.include_tasks: job-check.yml
  when: "trex_config.resources|length > 0"
