apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: testpmdmac-viewer-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - testpmdmacs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - testpmdmacs/status
  verbs:
  - get
