apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "examplecnf.openshift.io/v1",
          "kind": "TestPMD",
          "metadata": {
            "name": "testpmd-sample"
          },
          "spec": {
            "networks": [
              {
                "name": "vfdpdk1"
              }
            ]
          }
        },
        {
          "apiVersion": "examplecnf.openshift.io/v1",
          "kind": "TestPMDMac",
          "metadata": {
            "name": "testpmdmac-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.1
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: testpmd-operator.v0.1.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: TestPMDMac
      name: testpmdmacs.examplecnf.openshift.io
      version: v1
    - kind: TestPMD
      name: testpmds.examplecnf.openshift.io
      version: v1
  description: An operator to manage the TestPMD application
  displayName: TestPMD Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - examplecnf.openshift.io
          resources:
          - testpmds
          - testpmds/status
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - examplecnf.openshift.io
          resources:
          - testpmdmacs
          - testpmdmacs/status
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - k8s.cni.cncf.io
          resources:
          - network-attachment-definitions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: testpmd-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
                example-cnf-type: testpmd-operator
            spec:
              containers:
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                - --leader-election-id=testpmd-operator
                image: quay.io/krsacme/testpmd-operator:v0.1.2
                imagePullPolicy: IfNotPresent
                name: manager
                resources: {}
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - testpmd
  - nfv
  - cnf
  links:
  - name: Testpmd Operator
    url: https://testpmd-operator.domain
  maintainers:
  - email: skramaja@redhat.com
    name: Saravanan KR
  maturity: alpha
  provider:
    name: Red Hat
  replaces: testpmd-operator.v0.1.1
  version: 0.1.2
