apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: testpmd-lb-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testpmd-lb-operator-manager-role
subjects:
- kind: ServiceAccount
  name: conroller-manager
  namespace: system
