apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "examplecnf.openshift.io/v1",
          "kind": "LoadBalancer",
          "metadata": {
            "name": "loadbalancer-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.4.0+git
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: testpmd-lb-operator.v0.2.4
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: LoadBalancer
      name: loadbalancers.examplecnf.openshift.io
      version: v1
  description: LoadBalancer for FastData path traffic
  displayName: LoadBalancer
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - examplecnf.openshift.io
          resources:
          - loadbalancers
          - loadbalancers/status
          - loadbalancers/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - examplecnf.openshift.io
          resources:
          - cnfappmacs
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - k8s.cni.cncf.io
          resources:
          - network-attachment-definitions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: testpmd-lb-operator-controller-manager
      deployments:
      - name: testpmd-lb-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --enable-leader-election
                - --leader-election-id=testpmd-lb-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/rh-nfv-int/testpmd-lb-operator:v0.2.4
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources: {}
              serviceAccountName: testpmd-lb-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: testpmd-lb-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - example-cnf
  - cnf
  - testpmd
  - loadbalancer
  - nfv
  links:
  - name: Testpmd Lb Operator
    url: https://testpmd-lb-operator.domain
  maintainers:
  - email: skramaja@redhat.com
    name: '''Saravanan KR'''
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.2.4
