# permissions for end users to edit grouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: grout-operator
    app.kubernetes.io/managed-by: kustomize
  name: grout-editor-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - grouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - grouts/status
  verbs:
  - get
