---
version: ''
registry: quay.io
org: rh-nfv-int
image_pull_policy: IfNotPresent
privileged: false
command: ["trex-wrapper"]
environments: {}
network_resources: {}
enable_lb: true
lb_macs: []
trex_server: true
trex_app: false
