---
image_server: "quay.io/rh-nfv-int/trex-container-server@sha256:b30de0556968460781240d24c88903fdeb0ddf725994f43a999178448abde824"  # v0.2.3
image_app: "quay.io/rh-nfv-int/trex-container-app@sha256:5ab014537ac0353a4be49963246489bc45dedab85c5e693d555e89622df39e30" # v0.2.3
image_pull_policy: IfNotPresent
privileged: false
command: ["trex-wrapper"]
environments: {}
network_resources: {}
enable_lb: true
lb_macs: []
trex_server: true
trex_app: false

skip_annot: false
