---
image_server: quay.io/krsacme/trex-container-server:latest
image_app: quay.io/krsacme/trex-container-app:latest
image_pull_policy: IfNotPresent
privileged: false
command: ["trex-wrapper"]
environments: {}
network_resources: {}
