# permissions for end users to view testpmds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testpmd-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: testpmd-operator
    app.kubernetes.io/part-of: testpmd-operator
    app.kubernetes.io/managed-by: kustomize
  name: testpmd-viewer-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - testpmds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - testpmds/status
  verbs:
  - get
