---
galaxy_info:
  author: telcoci
  description: testpmd
  company: Red Hat
  license: license (Apache, BSD)
  min_ansible_version: 2.9
  galaxy_tags: []

dependencies: []

collections:
- operator_sdk.util
- kubernetes.core
