# permissions for end users to edit cnfappmacs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnfappmac-editor-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - cnfappmacs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - cnfappmacs/status
  verbs:
  - get
