# permissions for end users to edit testpmdmacs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testpmdmac-editor-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - testpmdmacs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - testpmdmacs/status
  verbs:
  - get
