# permissions for end users to view cnfappmacs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnfappmac-viewer-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - cnfappmacs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - cnfappmacs/status
  verbs:
  - get
