# permissions for end users to edit cnfappmacs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cnfappmac-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cnf-app-mac-operator
    app.kubernetes.io/part-of: cnf-app-mac-operator
    app.kubernetes.io/managed-by: kustomize
  name: cnfappmac-editor-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - cnfappmacs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - cnfappmacs/status
  verbs:
  - get
