apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testpmds.nfv.refarch.com
spec:
  group: nfv.refarch.com
  names:
    kind: TestPMD
    listKind: TestPMDList
    plural: testpmds
    singular: testpmd
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
