# permissions for end users to edit testpmds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: testpmd-operator
    app.kubernetes.io/managed-by: kustomize
  name: testpmd-editor-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - testpmds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - testpmds/status
  verbs:
  - get
