---
image: quay.io/krsacme/testpmd-container-app:latest
image_monitor: quay.io/krsacme/testpmd-container-app-monitor:latest
image_pull_policy: IfNotPresent
privileged: false
network_defintions: ""
network_resources: {}
environments: {}

termination_grace_period_seconds: 300

# mac workaround variables
mac_workaround_enable: false
mac_workaround_image: quay.io/krsacme/testpmd-container-app-mac-fix:latest
mac_workaround_version: "4.5"
mac_workaround_file: "sriov"
