---
registry: quay.io
org: rh-nfv-int
version: v0.2.0
image_pull_policy: IfNotPresent
privileged: false
network_defintions: ""
network_resources: {}
environments: {}

# mac workaround variables
mac_workaround_enable: false
mac_workaround_version: "4.5"
mac_workaround_file: "sriov"
