kind: Job
apiVersion: batch/v1
metadata:
  name: "job-{{ ansible_operator_meta.name }}"
  namespace: "{{ ansible_operator_meta.namespace }}"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        example-cnf-type: pkt-gen-app
{% if runtime_class_name is defined and runtime_class_name|length %}
      annotations:
        irq-load-balancing.crio.io: "disable"
        cpu-load-balancing.crio.io: "disable"
{% endif %}
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 56560
      serviceAccountName: trex-app-account
{% if runtime_class_name is defined and runtime_class_name | length %}
      runtimeClassName: "{{ runtime_class_name }}"
{% endif %}
      containers:
      - name: trex-app
        image: "{{ image_app }}"
        imagePullPolicy: "{{ image_pull_policy }}"
        securityContext:
          runAsNonRoot: true
          runAsUser: 56560
{% if run_deployment is defined and run_deployment == 1 %}
          readOnlyRootFilesystem: true
{% endif %}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: log-dir
          mountPath: /var/log/trex
        - name: tmp-dir
          mountPath: /tmp
        - name: dpdk-dir
          mountPath: /var/run/dpdk
{% if trex_profile_config_map %}
        - name: profile
          mountPath: /opt/trexprofile
{% endif %}
        env:
        - name: MODE
          value: "direct"
        - name: CR_NAME
          value: "{{ ansible_operator_meta.name }}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
{% for key, value in environments.items() %}
        - name: {{ key }}
          value: "{{ value }}"
{% endfor %}
        - name: TREX_SERVER_URL
          value: trex-server
{% if trex_profile_name %}
        - name: TREX_PROFILE_NAME
          value: "{{ trex_profile_name }}"
{% endif %}
{% if duration %}
        - name: DURATION
          value: "{{ duration }}"
{% endif %}
{% if packet_size %}
        - name: PACKET_SIZE
          value: "{{ packet_size }}"
{% endif %}
{% if packet_rate %}
        - name: PACKET_RATE
          value: "{{ packet_rate }}"
{% endif %}
        - name: run_deployment
          value: "{{ run_deployment }}"
{% if run_deployment is defined and run_deployment == 1 %}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the postStart handler"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the preStop handler"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8095
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8095
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /startz
            port: 8095
          initialDelaySeconds: 30
          periodSeconds: 10
{% endif %}
        resources:
          limits:
            cpu: 4
            memory: 1024Mi
          requests:
            cpu: 4
            memory: 1024Mi
        terminationMessagePolicy: FallbackToLogsOnError
      volumes:
      - name: varlog
        emptyDir: {}
      - name: log-dir
        emptyDir: {}
      - name: tmp-dir
        emptyDir: {}
      - name: dpdk-dir
        emptyDir: {}
{% if trex_profile_config_map %}
      - name: profile
        configMap:
          name: {{ trex_profile_config_map }}
{% endif %}
