---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: example-cnf
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Always
