apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        example-cnf-type: testpmd-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          securityContext:
            allowPrivilegeEscalation: false
          args:
            - "--enable-leader-election"
            - "--leader-election-id=testpmd-operator"
            - "--zap-encoder=console"
          image: controller:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
