# permissions for end users to view trexconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trexconfig-viewer-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - trexconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - trexconfigs/status
  verbs:
  - get
