# permissions for end users to view trexconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trexconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trex-operator
    app.kubernetes.io/part-of: trex-operator
    app.kubernetes.io/managed-by: kustomize
  name: trexconfig-viewer-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - trexconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - trexconfigs/status
  verbs:
  - get
