# permissions for end users to edit trexapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trexapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trex-operator
    app.kubernetes.io/part-of: trex-operator
    app.kubernetes.io/managed-by: kustomize
  name: trexapp-editor-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - trexapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - trexapps/status
  verbs:
  - get
