# permissions for end users to view trexapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trexapp-viewer-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - trexapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - trexapps/status
  verbs:
  - get
