---
image_pull_policy: IfNotPresent
privileged: false
network_defintions: ""
environments: {}

image_testpmd: "quay.io/rh-nfv-int/testpmd-container-app-testpmd@sha256:78e8ba58edc28cbac5888f3545383cbb3872171207aaffbf7972a5af8d07830a" # v0.2.2
image_listener: "quay.io/rh-nfv-int/testpmd-container-app-listener@sha256:7e2528c1b4e072dfcd8380fb784397067d79ee8a0a7d28883207f8dab22f6d2c" # v0.2.2

hugepage_1gb_count: 4Gi
memory: 1000Mi
cpu: 6
forwarding_cores: 4

memory_channels: 4
socket_memory: 1024

rx_queues: 1
rx_descriptors: 1024
tx_queues: 1
tx_descriptors: 1024

cnf_app_networks: []
packet_generator_networks: []
# ethpeer_maclist
packet_generator_macs: []
