---
image_pull_policy: IfNotPresent
privileged: false
network_defintions: ""
environments: {}

image_testpmd: "quay.io/rh-nfv-int/testpmd-container-app-testpmd@sha256:eca74e7cb50612e38a7712450ed123a7ed49f305b88f5e3b59d6368394535603"  # v0.2.3
image_listener: "quay.io/rh-nfv-int/testpmd-container-app-listener@sha256:050c5f7117bd6135af48cf742600bd30ab8448fe12fcab44960c1508c10327b1" # v0.2.3

hugepage_1gb_count: 4Gi
memory: 1000Mi
cpu: 6
forwarding_cores: 4

memory_channels: 4
socket_memory: 1024

rx_queues: 1
rx_descriptors: 1024
tx_queues: 1
tx_descriptors: 1024

cnf_app_networks: []
packet_generator_networks: []
# ethpeer_maclist
packet_generator_macs: []
