---
- name: requeue request
  requeue_after:
    time: 1m
- name: check if treconfig is available
  k8s_info:
    kind: TRexConfig
    api_version: examplecnf.openshift.io/v1
  register: trex_config
- name: fail if trexconfig is not created
  fail:
    msg: "wait for trexconfig resource"
  when: "trex_config.resources|length == 0"
- include_tasks: job-check.yml
  when: "trex_config.resources|length > 0"
