kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ ansible_operator_meta.name }}-app"
  namespace: "{{ ansible_operator_meta.namespace }}"
spec:
  replicas: {{ size | int }}
  selector:
    matchLabels:
      example-cnf-type: cnf-app
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
{% for network in networks %}
{% set outer_loop = loop %}
{% for count in range(network.count) %}
          {
            "name": "{{ network.name }}",
{% if network.mac|default([])|length == network.count %}
            "mac": "{{ network.mac[loop.index - 1] }}",
{% endif %}
            "namespace": "{{ ansible_operator_meta.namespace }}"
          }{% if loop.index < network.count or outer_loop.index < network_name_list|length %},{% endif %}
{% endfor %}
{% endfor %}
        ]'
      labels:
        example-cnf-type: cnf-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: example-cnf-type
                operator: In
                values:
                - lb-app
            topologyKey: kubernetes.io/hostname
      containers:
      - name: testpmd
        command: ["testpmd-wrapper"]
        args:
        - "--socket-mem {{ socket_memory }}"
        - "-n {{ memory_channels }}"
        - "--proc-type auto"
        - "--file-prefix pg"
        - "--"
        - "--disable-rss"
        - "--nb-cores={{ forwarding_cores }}"
        - "--rxq={{ rx_queues }}"
        - "--txq={{ tx_queues }}"
        - "--rxd={{ rx_descriptors }}"
        - "--txd={{ tx_descriptors }}"
        - "--auto-start"
{% for mac in ethpeer_maclist %}
        - "--eth-peer={{ loop.index -1 }},{{ mac }}"
{% endfor %}
        - "--forward-mode={{ forward_mode }}"
        image: "{{ image_testpmd }}"
        imagePullPolicy: "{{ image_pull_policy }}"
        securityContext:
{% if privileged %}
          privileged: true
{% else %}
          capabilities:
            add: ["IPC_LOCK", "NET_ADMIN"]
{% endif %}
        resources:
          limits:
            hugepages-1Gi: {{ hugepage_1gb_count }}
            memory: {{ memory }}
            cpu: {{ cpu }}
{% for key, value in network_resources.items() %}
            {{ key }}: {{ value }}
{% endfor %}
          requests:
            hugepages-1Gi: {{ hugepage_1gb_count }}
            memory: {{ memory }}
            cpu: {{ cpu }}
{% for key, value in network_resources.items() %}
            {{ key }}: {{ value }}
{% endfor %}
        volumeMounts:
        - name: hugepage
          mountPath: /dev/hugepages
        - name: log-dir
          mountPath: /var/log/testpmd
        - name: lib-dir
          mountPath: /var/lib/testpmd
        env:
        - name: NETWORK_NAME_LIST
          value: "{{ network_resources.keys()|list|join(',') }}"
        - name: TESTPMD_CPU_COUNT
          value: "{{ cpu }}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CR_NAME
          value: "{{ ansible_operator_meta.name }}"
{% for key, value in environments.items() %}
        - name: {{ key }}
          value: "{{ value }}"
{% endfor %}
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
      - name: log-dir
        emptyDir: {}
      - name: lib-dir
        emptyDir: {}
