kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ ansible_operator_meta.name }}-app"
  namespace: "{{ ansible_operator_meta.namespace }}"
spec:
  replicas: {{ size | int }}
  selector:
    matchLabels:
      app: testpmd
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
{% for network in networks %}
          {
            "name": "{{ network.name }}",
{% if network.mac|default() %}
            "mac": "{{ network.mac }}",
{% endif %}
            "namespace": "{{ ansible_operator_meta.namespace }}"
          }{% if loop.index < network_name_list|length %},{% endif %}
{% endfor %}
        ]'
      labels:
        app: testpmd
    spec:
      nodeSelector:
        examplecnf.openshift.io/testpmd: ""
      containers:
      - name: testpmd
        command: ["testpmd-wrapper"]
        args:
        - "--socket-mem {{ socket_memory }}"
        - "-n {{ memory_channels }}"
        - "--proc-type auto"
        - "--file-prefix pg"
        - "--"
        - "--disable-rss"
        - "--nb-cores={{ forwarding_cores }}"
        - "--rxq={{ rx_queues }}"
        - "--txq={{ tx_queues }}"
        - "--rxd={{ rx_descriptors }}"
        - "--txd={{ tx_descriptors }}"
        - "--auto-start"
{% for mac in ethpeer_maclist %}
        - "--eth-peer={{ loop.index -1 }},{{ mac }}"
{% endfor %}
        - "--forward-mode={{ forward_mode }}"
        image: "{{ image }}"
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add: ["IPC_LOCK", "NET_ADMIN"]
        resources:
          limits:
            hugepages-1Gi: {{ hugepage_1gb_count }}
            memory: {{ memory }}
            cpu: {{ cpu }}
{% for key, value in network_resources.items() %}
            {{ key }}: {{ value }}
{% endfor %}
          requests:
            hugepages-1Gi: {{ hugepage_1gb_count }}
            memory: {{ memory }}
            cpu: {{ cpu }}
{% for key, value in network_resources.items() %}
            {{ key }}: {{ value }}
{% endfor %}
        volumeMounts:
        - name: hugepage
          mountPath: /dev/hugepages
        env:
        - name: NETWORK_NAME_LIST
          value: "{{ network_resources.keys()|list|join(',') }}" 
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
