#!/bin/bash

set -ex

RUN_APP=${run_app:=1}

LOG_FILE="/var/log/testpmd/app.log"

# Wait till the /var/log/testpmd.log file is created
n=5
if [[ $RUN_APP == "0" ]]; then
    # add extra deploy for debugging
    n=600
fi
until [ "$n" -le 0 ]; do
    echo "Waiting for log file creation ($n)..."
    [ -e $LOG_FILE ] && break || sleep 2
    n=$((n - 1))
done
if [ $n -le 0 ]; then
    echo "ERROR: File $LOG_FILE not found, exit application"
    # TODO: Kill whole application
    exit 1
fi

TESTPMD_LOG_CHECK_STRING=${log_check_string:="lb packet forwarding"}
echo "Log file $LOG_FILE exists, wait for ${TESTPMD_LOG_CHECK_STRING} message"
n=120
until [ "$n" -le 0 ]; do
    echo "Waiting for TestPMD start log ($n)..."
    grep -q "$TESTPMD_LOG_CHECK_STRING" $LOG_FILE && break || sleep 5
    n=$((n - 1))
done
if [ $n -le 0 ]; then
    echo "ERROR: TestPMD is not started, waiting to configure timeout..."
    exit 1
fi

listener
