---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trex-server-rolebinding
  namespace: example-cnf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trex-server-role
subjects:
- kind: ServiceAccount
  name: trex-server-account
  namespace: example-cnf
