#!/bin/bash

set -e

if [ -z NETWORK_NAME_LIST ]; then
    echo "NETWORK_NAME_LIST is empty, exiting.."
    exit 1
fi

CORES=$(taskset -pc 1 | cut -d: -f2)

RUN_CONFIGURE=${run_configure:=1}
if [[ $RUN_SERVER != "1" ]]; then
    echo "Configure disabled for manual override, sleeping .."
    sleep infinity
fi

# Write TRex cfg file
trex-cfg-configure $CORES

# Read the number of cores from the trex cfg
# It is required as input via -c arg (for binary_search scripts of trafficgen)
CORE_COUNT=$(grep ' c: ' /etc/trex_cfg.yaml | cut -d: -f2 | xargs)
NUM_PORTS=$(grep ' port_limit: ' /etc/trex_cfg.yaml | cut -d: -f 2 | xargs)

# TREX_CPU env will be set on the pod spec with number of required cores
if [[ $((CORE_COUNT + 2)) != $TREX_CPU ]]; then
    # TEMP
    echo "CORES=$((CORE_COUNT + 2))"
    echo "TREX_CPU=$TREX_CPU"
    exit 1
fi

SERVER="/usr/local/bin/trex-server"
chmod +x $SERVER

RUN_SERVER=${run_server:=1}
if [[ $RUN_SERVER == "1" ]]; then
    echo "Starting TRex server ..."
    $SERVER $CORE_COUNT &
fi

# wait for trex server to be ready
count=60
num_ports=0
while [ ${count} -gt 0 -a ${num_ports} -lt $NUM_PORTS ]; do
    sleep 1
    num_ports=`netstat -tln | grep -E :4500\|:4501 | wc -l`
    ((count--))
done
if [ ${num_ports} -eq $NUM_PORTS ]; then
    echo "trex-server is ready"
else
    echo "ERROR: trex-server could not start properly, existing... "
    sleep infinity
    exit 1
fi

RUN_APP=${run_app:=1}
if [[ $RUN_SERVER == "1" && $RUN_APP == "1" ]]; then
    # leave the server running for 10s before starting application
    sleep 10
    echo "Running TRex application ..."
    run-trex
else
    echo "Skipping TRex application run, waiting ..."
    sleep infinity
fi

