#!/usr/bin/env python3

import os
import yaml
import sys
from kubernetes import client, config
from kubernetes.client.rest import ApiException

trex_cfg_template = [{
    "port_limit": 2,
    "version": 2,
    "interfaces": [],
    "port_info": [],
    "c": 0,
    "platform": {
        "master_thread_id": 0,
        "latency_thread_id": 0,
        "dual_if": [{
            "socket": 0,
            "threads": []
        }]
    }
}]

port_obj_l2_template = {
    "dest_mac": "",
    "src_mac": ""
}

CFG_FILE = "/etc/trex_cfg.yaml"

def main():
    cfg = trex_cfg_template.copy()

    # Ports allocated to TRex
    pci_list = get_pci()
    cfg[0]['interfaces'].extend(pci_list)
    cfg[0]['port_limit'] = len(pci_list)

    core_list = cores()
    cfg[0]['c'] = len(core_list) - 2
    cfg[0]['platform']['master_thread_id'] = core_list[0]
    cfg[0]['platform']['latency_thread_id'] = core_list[1]
    cfg[0]['platform']['dual_if'][0]['threads'] = core_list[2:]

    src_mac = get_src_mac()
    if not src_mac:
        print("ERROR: Source mac address is not available, exiting...")
        sys.exit(1)

    dst_mac = get_dst_mac()
    if not dst_mac:
        print("ERROR: Destination mac address is not available, exiting...")
        sys.exit(1)

    if len(dst_mac) != len(src_mac):
        print("ERROR: Source (%s) and Destination (%s) mac list size is "
            "different, exiting..." % (','.join(src_mac), ','.join(dst_mac)))
        sys.exit(1)

    if len(pci_list) != len(src_mac):
        print("ERROR: PCI device list (%s) and Source mac (%s) mac list size is "
            "different, exiting..." % (','.join(pci_list), ','.join(dst_mac)))
        sys.exit(1)

    for idx in range(len(pci_list)):
        port_obj = port_obj_l2_template.copy()
        port_obj['src_mac'] = src_mac[idx]
        port_obj['dest_mac'] = dst_mac[idx]
        cfg[0]['port_info'].append(port_obj)

    print(trex_cfg_template)
    with open(CFG_FILE, "w") as f:
        yaml.safe_dump(cfg, f)

def cores():
    core_string = sys.argv[1]
    core_list = []
    for item in core_string.split(','):
        if '-' in item:
            range_parts = item.split('-')
            for c in range(int(range_parts[0]), int(range_parts[1]) + 1):
                core_list.append(c)
        else:
            core_list.append(int(item))
    return core_list

def get_pci():
    networks = os.environ['NETWORK_NAME_LIST']
    network_list = networks.split(',')
    pci_all = []
    for net in network_list:
        pci_env = "PCIDEVICE_" + net.replace('/', '_').replace('.', '_').upper()
        pcis = os.environ[pci_env]
        print("pcis = %s" % pcis)
        pci_list = pcis.split(',')
        pci_all.extend(pci_list)
    return pci_all

def get_src_mac():
    podinfo = "/etc/podnetinfo/annotations"
    obj = []
    macs = []
    with open(podinfo) as f:
        for line in f:
            name, var = line.partition("=")[::2]
            if name == "k8s.v1.cni.cncf.io/networks":
                obj = yaml.safe_load(yaml.safe_load(var))
    for item in obj:
        print(item)
        if 'mac' in item:
            macs.append(item['mac'])
        else:
            print("TODO: Implement mac fetching DPDK application")
    return macs

def get_dst_mac():
    group = "examplecnf.openshift.io"
    version = "v1"
    namespace = "example-cnf"
    plural = "testpmdmacs"

    config.load_incluster_config()
    custom_api = client.CustomObjectsApi()
    try:
        response = custom_api.list_namespaced_custom_object(group, version, namespace, plural)
    except ApiException as e:
        return []

    macs = []
    for item in response['items']:
        print(item['spec']['nodename'])
        for resource in item['spec']['resources']:
            macs.append(resource['devices'][0]['mac'])
    return macs

if __name__ == "__main__":
    main()
