---
size: 1

hugepage_1gb_count: 4Gi
memory: 1000Mi
cpu: 6
forwarding_cores: 4

forward_mode: mac

memory_channels: 4
socket_memory: 1024

rx_queues: 1
rx_descriptors: 1024
tx_queues: 1
tx_descriptors: 1024

# pci devices for "-w" parameter should be obtained from this networks
# testpmd application entrypoint script should get pci and then run testpmd
networks: []

ethpeer_maclist: []
