apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: grout-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: An operator to manage the Grout application
  displayName: Grout Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAACAAAAAgEAYAAAAj6qa3AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGYktHRAAAAAAAAPlDu38AAAAJcEhZcwAABCoAAAQqAKd4QIUAAAAHdElNRQfoAwcSCQrCAVRvAAAAAW9yTlQBz6J3mgAAB+RJREFUaN7tmWtwVdUVx38nyc0lgVBySQiFJKQYUARBUB4mYsWEUkNBq0IAtUAptji2lY6WUobO6DCttjOSlKnWNhEKpoylUEkJQ2spbQ3ESmhUwiNgoAiBGMy5eZKE5Ob0w3+fmDD9kHtDnM6U/WXd/Vh7rfVfa6+99rlwo/1/NytURv9BUWcEAEMYDEAdV82CTwwNAODx3Q5Ae2/3t5sBCDcaBmgxE82GRhu5syTXdzQ0O8JCBcAZC8BABhjDLYDEB4kAmH9W1HPYSGj3z+glsF9wBRjD2wAi7qAT4MtN2i8xl0gj9z2jR4gtaAD8Qt5iEADNxAPE3CqDX0rXqgUHqAZwhjHcMJYZfuu/y/V7zfilHgDAeQAnQf3s/QJ84+2SF7PVREazfdzoFWQLmsE/2+j3SzMQD/BUlUJ9aa188Ug2HQCxW3Ukxv5FHtuRQTiAM83ZaPhbjSJreqj1vkJ9wb/wApy6jSYA+w31dx6W5ltfkdxN48xRw5cQnD1BR4BTZH4kAcTPVWg+niy6aYJoU4sAyE2U58aPphjAWUGDMfFpQ3/QU5OwJgBnmc74+Bjtl+uX55t/pnWbPFr92Fo8APE55igG3XoNgH+5+XGlO506SAaGvyUP792gkFw8SQA4ZxSqOXcxDYCjkpiSRz3A6jfl2dVvyKMpeZ3hAJRpv5yZZp8EeXixjyiAvZbWh8/V+NTPuRHgf6SfACDtGgDCACZukIcq36QWoGGuAMn8jRQqLNK8P1njw18Xc/4eAZNVqiORdUwhn79ZfMNzJcefIP7C01qX+br4GlZrXeUR9SfOc48Sd/YTAM5S8yPC0ABAfKkMq6nRBRe5VgrHvSOFT78rD4Lo9Nlan1goA5c1aJ9lrRof+Q/tP/0W16MK8dN/ksfjKjUeuVaTNXGSG19gkjLOY/0EAB8ZGukiAtC+UoZGZunMBvKkaMcyKR49s4vfAqh7XBI9HypZzoiUwTPqzObvKWnWLekJXHSmOu0LxB/4neR7X5X8qylunWCN6icAOlquGQgAnH1ZiozKlic6/6zJioWid5dTada3ApSsVoSUXBLfr/4tA/OOiL/kLCcBSl7VkXI1vPuMOqfSqQLoNAE/6mnNn80SEBB2uZ8ACHeTixGk6+hwrjqJi+TJ1LcVIdu/K4MySkgBSJui5BVoUCR4h5hbY7+AzK8Wf9Sj3AMQ+KOyetqDAipjnyJj+3piAcYskuYjT0v+4Zcw90LnB/0EwNCKawDwAJQnq3MiSkfgiTIpXvycdt5tCZDsq6KTLgqA0aagLdgiuq1c4zcnyfMTdxg+48/dxwVAcYuAfSJTehxv1dk/ts49mrH3BgdA8IWQBHmcGgDa5cl0Ex/5X5ThP+q0kgAK73Q+BojZo5J2ZYwkTqqzPg+wpM05ARBRL0N2ZWj+7Z0mMh62RgA0ZjiXAB6oleHPvSb69UoBc6iQRunlG2306mWL6O1Ct5kKrt0NOSWfg7+X4TkxOtNZx5wygN2Xdd9fiZOHMieIb/O3nQsAgVMmqRmVi85qfoFfof7zXU4FQOfHMnj2DlNyv8YegEPjrUeNXnZwhve5ua81u9H0WwHCqu0qgCFHbZPF7SaAWZtsP8C7ttYnLuziq+5OUw/YtQAfvCx6z012S/f9B//W7wEIe9E2pvpFwgmxhfwc7gJCCkaYe7vDLXW7VIoE2HhInaR9XABYOJBhAJ1ruh49quxuUwT84biOVsX3rZEAz/7EqTfr3MiTvAhfpJEbYgv5Oew2X5QUsH7a3WDXoIQlMmSWKZDS0mT4mhdkeHSKrscBPoX2UxPEN7lY9L4K5zxA3P6uN4S5d/pq+HUDwG2mAgvvquC8ADML1Gm5ovFn98mD8+cpQvJbVRDlrRUgS3Jl0vpR0qz9IwGaXulGlPMNI+c6tesGAEMACEjhsOky6IEfSsKBKo0X5MjAX39P419tlCnZJ0S3bdDjaMsIzf/dRND8k0ZKjaEB/lea/1ui9kVDLwCkbrc/ASiLsesBMkptG+A7EUqG5ePsGoB1y5UM15XYdQAn47T+mTuUPO/3iq90iuZTsE3Wsxu4Li3oa/Da5uiZG971CWsgQOYZ9Qc8I/rkNnk4+RZiANbEKRKKNjt6Zm+2XgF4f5fGn68XX9UcSRmcr5xw70qNb1ll3ibuUQg5IkL/Juhm74eNAkMBvLuk6LyVmhy7V6q175Rhi8fp3ir6W5cC7geWAMCeh9RZZGr9tirtN6ZeR2HedB0lTyrJfTO8zwD4dX9bXaVHA8CEg1J0/GR5an203vkrvilJH+5AtXqE5TNAntc+5pNYmGLy1CpVisu3yMfPn9N+k1eo8Lr5Vjf/27X0qYV8BCx9FXYcNz1FA3xlmhQtzdSb4EWPAAlkijKQdwBojm0yfDHaxz9F1LhkkOMHaPyFAPzxVC2eek773D9St0y5e+269YzDZ9Vs893fvgwQe5eSU3GtktPX5tj13eeDB9pWZES4HlYyXFWt/v4j2n/Q0r4mw9CvQTf0rwIkme8xjR3yyF8fck22ngRCKViGGb5O0+8EeGuOfByZrtOf4u1r9R9yKWzXdN/BW6AjMPSf+iJz8QVjcnRsXd8UtM+ZHw5A2JcE8BhHr8vzpsK8cp/vps8aAIW21+zQpg8eYMWbBcrPVmzbp+qHJEdH4dO/yNyLz/1CpQiJ8qX2GL3RbrRetv8ABTa0S/ux8acAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - grout
  - nfv
  - cnf
  links:
  - name: Grout Operator
    url: https://grout-operator.domain
  maintainers:
  - email: telcoci@redhat.com
    name: Telco CI
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
