# permissions for end users to view loadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: loadbalancer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: testpmd-lb-operator
    app.kubernetes.io/part-of: testpmd-lb-operator
    app.kubernetes.io/managed-by: kustomize
  name: loadbalancer-viewer-role
rules:
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - loadbalancers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - examplecnf.openshift.io
  resources:
  - loadbalancers/status
  verbs:
  - get
