---
- set_fact:
    network_resources: {}
    network_name_list: []

- name: Validate the CPUs and forwarding cores
  fail:
    msg: "{{ forwarding_cores }} should be lesser than {{ cpu }}"
  when: forwarding_cores|int >= cpu|int

- name: print network list
  debug:
    var: networks

- name: print resource list
  debug:
    var: resources

- name: Check if networks parameter is empty
  fail:
    msg: "networks or resources parameter is required"
  when: 
    - networks|length == 0
    - resources|length == 0

- name: initialize eth_peer var
  set_fact:
    eth_peer: ""
- name: construct eth_peer
  set_fact:
    eth_peer: "{{ eth_peer }}{{ idx|string }},{{ item }};"
  loop: "{{ ethpeer_maclist }}"
  loop_control:
    index_var: idx
- name: create configmap with cnf-app run script
  kubernetes.core.k8s:
    name: cnf-run
    namespace: "{{ ansible_operator_meta.namespace }}"
    kind: ConfigMap
    definition:
      data:
        run: |
          {{ lookup('file', 'run') }}

- name: "Parse network"
  include_tasks: network-parse.yaml
  when: networks|default([])|length > 0
  loop: "{{ networks }}"
  loop_control:
    loop_var: network_item

- name: "Parse resources if defined and when sriov network is not defined"
  set_fact: 
    network_resources: "{{ network_resources | combine({item.name: item.count}) }}"
  loop: "{{ resources }}"
  when:
    - networks|default([])|length == 0
    - resources|default([])|length > 0

- name: print network resources map
  debug:
    var: network_resources

- name: Create ServiceAccount for TestPMD resource
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'service_account.yml') }}"

- name: Create Role for TestPMD resource
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'role.yml') }}"

- name: Create RoleBinding for TestPMD resource
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'role_binding.yml') }}"

- name: Create TestPMD deployment
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.yml') }}"

- name: Create PodDisruptionBudget for LoadBalancer pod
  k8s:
    state: present
    definition: "{{ lookup('template', 'pdb.yml') }}"
