---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-examplecnf-openshift-io-v1-cnfappmac
  failurePolicy: Fail
  name: mcnfappmac.kb.io
  rules:
  - apiGroups:
    - examplecnf.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cnfappmacs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-examplecnf-openshift-io-v1-cnfappmac
  failurePolicy: Fail
  name: vcnfappmac.kb.io
  rules:
  - apiGroups:
    - examplecnf.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cnfappmacs
  sideEffects: None
