apiVersion: v1
kind: List
items:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: "{{ ansible_operator_meta.name }}-default-deny-egress"
      namespace: "{{ ansible_operator_meta.namespace }}"
    spec:
      podSelector:
        matchLabels:
          control-plane: controller-manager
      policyTypes:
        - Egress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: "{{ ansible_operator_meta.name }}-default-deny-ingress"
      namespace: "{{ ansible_operator_meta.namespace }}"
    spec:
      podSelector:
        matchLabels:
          control-plane: controller-manager
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: "{{ ansible_operator_meta.name }}-intra-namespace"
      namespace: "{{ ansible_operator_meta.namespace }}"
    spec:
      podSelector:
        matchLabels:
          control-plane: controller-manager
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: "{{ ansible_operator_meta.namespace }}"
      egress:
        - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: "{{ ansible_operator_meta.namespace }}"
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: "{{ ansible_operator_meta.name }}-to-openshift-dns"
      namespace: "{{ ansible_operator_meta.namespace }}"
    spec:
      podSelector:
        matchLabels:
          control-plane: controller-manager
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: "{{ ansible_operator_meta.namespace }}"
      egress:
        - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: "openshift-dns"
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: "{{ ansible_operator_meta.name }}-from-openshift-dns"
      namespace: "{{ ansible_operator_meta.namespace }}"
    spec:
      podSelector:
        matchLabels:
          control-plane: controller-manager
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: "openshift-dns"
      egress:
        - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: "{{ ansible_operator_meta.namespace }}"