---
apiVersion: v1
kind: List
items:
  - apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: cnf-app-pdb-min
      namespace: "{{ ansible_operator_meta.namespace }}"
    spec:
      minAvailable: "{{ (size|int == 1)|ternary(1,2) }}"
      selector:
        matchLabels:
          example-cnf-type: cnf-app
  - apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: cnf-app-pdb-max
      namespace: "{{ ansible_operator_meta.namespace }}"
    spec:
      maxUnavailable: "{{ (size|int == 1)|ternary(0,1) }}"
      selector:
        matchLabels:
          example-cnf-type: cnf-app
