---
apiVersion: v1
kind: List
items:
  - apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: cnf-app-pdb-min
      namespace: "{{ ansible_operator_meta.namespace }}"
    spec:
      minAvailable: 0
      selector:
        matchLabels:
          example-cnf-type: cnf-app
