name: PR Validation

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: quay.io

defaults:
  run:
    shell: bash

jobs:
  validate-pr:
    # Build only when the PR comes from a branch in the same repo or forced
    if: github.repository == github.event.pull_request.head.repo.full_name || inputs.force_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Build All
        run: |
          env
          set -x
          URL="${{ github.event.pull_request._links.self.href }}"
          echo "URL=$URL"
          if curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" "$URL"|jq -r .body|grep -qi '^Test-Hints:.*force-build=true'; then
              FORCE=true
          else
              FORCE=false
          fi
          echo "sha=${{ github.event.pull_request.head.sha }}"
          SHA=$(cut -c1-8 <<< ${{ github.event.pull_request.head.sha }})
          make version
          echo "force_build=${{ github.event.inputs.force_build }}"
          make all SHA=${SHA} DATE=pr${{ github.event.number }} FORCE=$FORCE
